apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/saivikram2020251/frontend:latest
---

apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    tier: frontend
spec:
  containers:
    - name: nginx
      image: docker.io/nginx