---
apiVersion: v1
kind: Pod
metadata:
  name: pod-01
spec:
  containers:
    - name: nginx
      image: docker.io/nginx
      env:
        - name: URL
          value: example.com
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  URL: google.com
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-02
spec:
  containers:
    - name: nginx
      image: docker.io/nginx
      env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: game-demo
              key: URL
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-03
spec:
  containers:
    - name: nginx
      image: docker.io/nginx
      envFrom:
        - configMapRef:
            name: game-demo

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-demo
data:
  NAME: SGVsbG9Xb3JsZAo=
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-04
spec:
  containers:
    - name: nginx
      image: docker.io/nginx
      envFrom:
        - secretRef:
            name: secret-demo

