apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: docker.io/nginx
---
#12:41
#kubectl exec -it debug -- bash
# curl nginx

apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  containers:
    - name: debug
      image: docker.io/rkalluru/debug
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80
---
#kubectl exec -it debug -n kube-system --bash
#curl nginx doesn't work because both are different namespaces
#curl nginx.kube-system.svc.local.cluster
apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: kube-system
spec:
  containers:
    - name: debug
      image: docker.io/rkalluru/debug
---
#kubectl get svc - to check services are running
#kubectl describe svc nginx-up - to describe the service
# docker inspect containerid
#curl ip:3060
apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


---
#for cname records advantage dns request will be less
apiVersion: v1
kind: Service
metadata:
  name: myedu
spec:
  type: ExternalName
  externalName: www.columbia.edu