apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type  }}
  selector:
    app: {{ .Values.appName }}
  ports:
    protocol: TCP
    port: 80 #{{ .Values.service.port  }}
    targetPort: 80 #{{ .Values.service.port  }}